name: <your project name>
services:
    samba:
        stdin_open: true
        tty: true
        container_name: samba
        environment:
            - TZ=Asia/Shanghai
        ports:
            - 139:139
            - 445:445
        volumes:
            - /Users/zen/Downloads:/mount
        image: dperson/samba
        command: -p