name: samba
services:
    samba-server:
        container_name: samba-server
        ports:
            - 137:137/udp
            - 138:138/udp
            - 139:139
            - 445:445
        volumes:
            - /Users/zen:/share
        image: samba-server